### ISSUE TITLE
TPMImport to LocalMachine seem broken on Win11

### ISSUE THREAD

**Issue by forderud** [glueckkanja-pki/TPMImport#16]
I'm experiencing an error when attempting to import a PFX to the LocalMachine store when testing on Windows 11. TMPImport to CurrentUser, on the other hand, works just fine. Not sure it the problem is caused by Hyper-V or this project, but I still want to report it to be on the safe side.

Error message when testing from an admin command prompt:
```
C:\Users\User\Desktop>net6.0\TPMImport.exe -v ClientCert.pfx
PFX to TPM Importer
Creating RSA CngKeyObject with TPM-Import-Key-F6349A73DF0C3AFD9111985ADE743327C4358AEE
Key is reported as Machine Key (always false): True; Key Is Closed: False; Is Invalid: False; Export Policy: None; Is Ephemeral: False
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at DotNetCode.CertificateExtensionsCommon.GuessKeySpec(CngProvider provider, String keyName, Boolean machineKey, CngAlgorithmGroup algorithmGroup) in C:\Dev\TPMImport\DotNetCode\CertificateExtensionsCommon.cs:line 53
   at DotNetCode.CertificateExtensionsCommon.CopyWithPersistedCngKeyFixed(X509Certificate2 publicCert, CngKey cngKey) in C:\Dev\TPMImport\DotNetCode\CertificateExtensionsCommon.cs:line 35
   at TPMImport.Program.Main(String[] args) in C:\Dev\TPMImport\Program.cs:line 144
```
Certificate used for testing: [ClientCert.zip](https://github.com/glueckkanja-pki/TPMImport/files/9882390/ClientCert.zip)

The same problem is both from the current `master` (0baff79240c356d64f81bcfc0fdae1a7f7b4335a) as well with the 1[.1 release binaries](https://github.com/glueckkanja-pki/TPMImport/releases/tag/v1.1) from December 8 2020. It is therefore not caused by a recent regression.

**Comment by bb-froggy** [comment]
I believe I have tested this on a Hyper-V VM and it did work. I also noticed the following in your output:
"Key is reported as Machine Key (always false): True"
Maybe it isn't the Hyper-V itself, but the Windows version? Have you tested importing the certificate with certutil in your Hyper-V session? I currently have trouble with my Hyper-V and cannot test myself.

**Comment by forderud** [comment]
This problem appear to the `IsMachineKey` function not correctly detecting machine key in all scenarios. This triggers a later failure when attempting to open the key in the `GuessKeySpec` function.

I've just completed some testing on my end and are observing the following on my 20H2 Win10 x64 computer:
| Scenario | IsMachineKey | GetProperty("Key Type"..) |
|-----------|----------------|-----------------------------|
| CurrentUser on HW | False | [0, 0, 0, 0] |
| LocalMachine on HW | False | [1, 0, 0, 0] |
| CurrentUser in VM | False | [0, 0, 0, 0] |
| LocalMachine in VM | True | [32, 0, 0, 0] |

**Comment by forderud** [comment]
You're right @bb-froggy this problem seem tied to Windows 11 and not to Hyper-V VMs. I'm observing the exact same problem both when testing on physical Win11 HW and a Win11 VM. I've therefore updated the issue title and the comments above.
