### ISSUE TITLE
TPM key leakage problem

### ISSUE THREAD

**Issue by forderud** [glueckkanja-pki/TPMImport#4]
I'm experiencing problems with what appears to be key leakage in the TPM chip after running `TPMImport` and afterwards deleting the certificate from Windows certificate manager.

Steps to reproduce:
1. Run `TPMImport.exe -user MyCert.pfx ""` to import the MyCert certificate.
2. Run `certutil -user -csp TPM -key` and verify that a `TPM-Import-Key-<thumbprint>` line is displayed with thumbprint matching MyCert.
3. Open `certmgr.msc` and delete MyCert from the "Current User\Personal" (My) store.
4. Run `certutil -user -csp TPM -key` again, and observe that the `TPM-Import-Key-<thumbprint>` line is still displayed, despite the certificate having been deleted.

Any ideas on how to tackle this problem?

**Comment by bb-froggy** [comment]
I have also seen this. I selected the cert's thumbprint as container name, therefore you also cannot import the same certificate multiple times.

But there is also `certutil -delkey`, that's how I solved this when debugging.

**Comment by forderud** [comment]
> But there is also `certutil -delkey`, that's how I solved this when debugging.

Thanks a lot for the advise. I hereby confirm that `certutil -user -csp TPM -delkey TPM-Import-Key-<thumbprint>` seem to clean up the otherwise leaking TPM key.

Would it be possible to at least document this limitation at the project front-page, so that users at least are informed about the need for manual TPK key cleanup?

**Comment by bb-froggy** [comment]
Good idea, I will add that next week. And thanks for testing!

But I want to make clear that this is not a limitation of TPMImport as far as I can see, but seems to be Windows behavior. We don't want to let dirt stick on this fine project ;-). Although I doubt it, maybe it has a good reason; the behavior is different for other KSPs that I know, but perhaps there can be multiple references to the same TPM key and Windows cannot count them or something the like.

**Comment by forderud** [comment]
Might very well be. I'm new to Windows certificate management and key storage, so I don't really know much about how it's supposed to behave. Just want to store some certificates securely in TPM on Windows, and was surprised by how complex it turned out to be.

**Comment by forderud** [comment]
I've now tested the "_Certificate Enrollment with the Platform Crypto Provider_" sample instructions that's included in the [TPM Platform Crypto-Provider Toolkit](https://www.microsoft.com/en-us/download/details.aspx?id=52487) "_Using the Windows 8 Platform Crypto Provider and Associated TPM Functionality_" document. This sample seem to suffer from the same TPM key leakage problem with a `tq-<guid>` key persisting in the TPM also after deleting the certificate from the  "Current User\Personal" (My) store.

**Comment by bb-froggy** [comment]
I believe there is nothing we can do about the problem but warn that it happens. I just did that on the main page, so I'll close this issue.

If somebody finds that we need to change the way the key is imported and then it is properly deleted upon certificate deletion, we can of course re-open this issue and fix this :-).

Thanks, @forderud , for the research around this issue and for documenting information around it.
